print("     ^     ")
print("   /   \ ")
print("  /     \   ")
print(" /       \ ")
print("/_________\ ")
print("|   ___    | ")
print("|  |   |   | ")
print("|__|___|___| ")


print("      ^   ")
print("    /   \ ")
print("   ******* ")
print(" *         *")
print("*  0     0   *")
print(" *     >   *")
print("  *  \__/ *")
print("   *******")

print("# # # #")
print(" # # # #")
print("# # # # ")
print(" # # # #")
print("# # # # ")
print(" # # # #")

print("   *   ")
print("  ***  ")
print(" ***** ")
print("*******")
print("   |   ")

print("    **    **    ")
print("  *    * *    *  ")
print("*       *       * ")
print(" *             *  ")
print("  *           *    ")
print("   *         *    ")
print("    *       *    ")
print("     *     *   ")
print("       *  *   ")
print("        **   ")


print(" /\_/\ ")
print("( o.o )")
print(" > ^ < ")
